name: CI
on:
  push:
    branches:
      - master
    tags:
      - v1

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
       matrix:
         os: [ubuntu-18.04, ubuntu-16.04]
    steps:
    - uses: actions/checkout@v2  #チェックアウトするってどう言うことだ？
    - name: Hello World
      run: echo "Hello World"